### ISSUE TITLE
Can PhotoTags Syncronizer convert?

### ISSUE THREAD

**Issue by gwydionjhr** [Nordlien/PhotoTags-Synchronizer#3]
I'll preface this by saying: I'm not a developer.

I have almost 30,000 images tagged using WLPG and I'm looking for a way of converting the Microsoft People Tags to the Metadata Working Group Face Regions.

It appears that your PhotoTags Synchronizer has put a GUI on EXIFTool.  Is this correct?

Does it include this extension?: https://sourceforge.net/p/exiftool/code/ci/master/tree/config_files/convert_regions.config 

I am getting an error "Exiftool failed" and "Wildcards don't work in the directory..."

![image](https://user-images.githubusercontent.com/59325766/184960007-21b3d772-4de4-41cf-8132-fed069040277.png)

And if I try opening a folder with a large number of pictures, PhotoTags Syncronizer crashes.

This app appears to have a huge amount of potential, I'd love to help you work out the bugs.

**Comment by Nordlien** [comment]
Question: I have almost 30,000 images tagged using WLPG and I'm looking for a way of converting the Microsoft People Tags to the Metadata Working Group Face Regions. 
Answer: I have converted / fixed 10000+ pic using my tool, using tags from WLPG and Microsoft Photos, and Google Photos. 
Feedback: How many picture in a folder? I tested with 1000+

Question It appears that your PhotoTags Synchronizer has put a GUI on EXIFTool. Is this correct?
Answer: Yes, that's right

Question: Does it include this extension?: https://sourceforge.net/p/exiftool/code/ci/master/tree/config_files/convert_regions.config
Feedback: Are you using a different config file for your exiftool? Different from original config that exiftool is shipped with? 
I have only tested with original config that exiftool

Question: I am getting an error "Exiftool failed" and "Wildcards don't work in the directory..."
Answer: Are you able to reproduce it. If I can get some files, how to or other info to reproduce it, I can help fix it.

Thanks for your feedback. I have only been testing on my computer, and this the first release. So thanks for helping out. Let's try to find the issue together.

**Comment by Nordlien** [comment]
Question: Can PhotoTags Syncronizer convert?
Answer: Yes, in theory it can convert from any format to any format. Since the application use  open source tools and/or you can use your favorite tool to convert. 

- Step 1: Select Run app/Command Batch or press F6 after select all the files you want to select. 
![image](https://user-images.githubusercontent.com/72686779/185558560-1369ed4e-9c1c-409b-af63-de89db6d8318.png)

- Step 2: Then you can tell how you want the images and videos should be converted:
![image](https://user-images.githubusercontent.com/72686779/185558501-967af41d-f505-4bf0-b6fc-b084cf11b2a6.png)

Tell how to convert:
1. Select "Run batch..."
2. Write what "tool" to use for image conversion. Default magick.exe, that are included in this package.
3. Write how to convert, or extensions what to convert to. 
4. Write what "tool" to use for video conversion. Default ffmpeg.exe, that are included in this package.
5. Write how to convert, or extensions what to convert to.

**Comment by gwydionjhr** [comment]
I’m sorry for the delayed response.  I was away for vacation for 10 days.  I’m back and ready to figure this thing out.  Once I understand how it works, I think I’m going to make a step-by-step how to for YouTube, as I know there are other folks in the same boat as me.  IE: Not skilled enough at scripting to use EXIF Tool on it’s own, but stuck with huge libraries that were built and organized using Windows Photo Gallery and it’s people tagging.

I uninstalled my previous verison, rebooted and re-installed PTS from the Windows Store.  Here’s what I get when I point it at my test folder.

***@***.***

Is that expected?  It didn’t ask for Private and Public permissions like it did the first time I installed it.  On my first install two weeks ago, not knowing what was required I only gave it access to one of the two options (I can’t recall exactly which)

Regards,
Joel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Nordlien** [comment]
Me: Thanks for replay, I happy to help.

You: I’m sorry for the delayed response.  I was away for vacation for 10 days.  I’m back and ready to figure this thing out.  Once I understand how it works, I think I’m going to make a step-by-step how to for YouTube, as I know there are other folks in the same boat as me.  

Me: No worries for waiting, I will help you when I get answers and when I find time. However, so far I have no clue where it crash, so anything that can help me to understand the issue would be super great. If you may create a screen recording or send log files that very good.

You: IE: Not skilled enough at scripting to use EXIF Tool on it’s own, but stuck with huge libraries that were built and organized using Windows Photo Gallery and it’s people tagging. 

You: I uninstalled my previous version, rebooted and re-installed PTS from the Windows Store.  Here’s what I get when I point it at my test folder. 

Me: I have add some more try / catch - in other words remove some cases where it may crash and to avoid it.
Question: What do you get? I'm not sure I understand. Any error message?? But Youtube Video or something would be great.

***@***.***

You: Is that expected?  It didn’t ask for Private and Public permissions like it did the first time I installed it.  On my first install two weeks ago, not knowing what was required I only gave it access to one of the two options (I can’t recall exactly which)
Me: I allow both, if you are at home, you get access to private network, so the app can access internet true Windows Firewall, when you working outside Home, allow access for public internet.

**Comment by Nordlien** [comment]
Hi, will you test the new release. Looks as some calls to windows API Get Thumbnail for videos crash randomly. This call is removed and replaced with another call.
