### ISSUE TITLE
Error opening EXIFTO~1.TXT in AppData [set PDF keywords]

### ISSUE THREAD

**Issue by cao-muc** [Nordlien/PhotoTags-Synchronizer#4]
**Describe the bug**
I tried to use your tool as a gui for exiftool to apply pdf-keywords (xmp) to pdf-files, but it failed to do so (see error text below).

**To Reproduce**
1. Choose one or more PDF-files
2. Keywords (*): anything
3. save changes into files
5. See error message below

**Expected behavior**
Normally, it should put one or more keywords into xmp pdf metadata like in command line use.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
"Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-06.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-06.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-06.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-06.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:02
Last Write Time: 18.06.2022 20:43:58
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-22.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-22.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-22.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-33-22.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:02
Last Write Time: 18.06.2022 20:43:55
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-34-40.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-34-40.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-34-40.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-34-40.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:04
Last Write Time: 18.06.2022 20:43:54
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-36-23.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-36-23.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-36-23.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-36-23.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:07
Last Write Time: 18.06.2022 20:43:51
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-07.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-07.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-07.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-07.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:07
Last Write Time: 18.06.2022 20:43:52
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-55.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-55.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-55.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-43-55.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:07
Last Write Time: 18.06.2022 20:43:52
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-46-34.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-46-34.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-46-34.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-11-46-34.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:09
Last Write Time: 18.06.2022 20:43:47
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-00.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-00.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-00.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-00.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:23
Last Write Time: 18.06.2022 20:43:38
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-42.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-42.pdf, Error occured, File is locked (RW)
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-42.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-42.pdf
File Status: 
File Attributes: Archive
Creation Time: 23.12.2022 10:30:29
Last Write Time: 23.12.2022 11:58:23
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-58.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-58.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-58.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-46-58.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:25
Last Write Time: 18.06.2022 20:51:56
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-06.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-06.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-06.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-06.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:26
Last Write Time: 18.06.2022 20:43:29
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------

Issue: Failed write Xtra Atom property to file.
File Name:   D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-14.pdf
File Status: Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-14.pdf, Error occured
Error message:Failed to write Microsoft's own Xtra Atom Propery on file.: D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-14.pdf
------

Issue: EXIFTOOL.EXE failed write to file.
File Name:  D:\Dokumente\Eingang\2017\Schlüsselworte\2017-05-23-13-47-14.pdf
File Status: 
File Attributes: Archive
Creation Time: 15.10.2022 15:23:26
Last Write Time: 18.06.2022 20:48:18
Error Message: Error opening arg file C:\Users\danie\AppData\Local\PHOTOT~1\EXIFTO~1.TXT

------
"

Thank you for helping!

**Comment by Nordlien** [comment]
Hi, thanks for using PhotoTags-Synchronizer

Seems Microsoft don't support writing Xtra Atom to PDF files. Microsoft Xtra Atom is an old windows standard from Microsoft to store information on media files, and is more or less not supported anymore. 

When writing to the Media files and also PDF files, the program uses EXIFtool to write standard xmp information to the file, in addition use Windows functions to write Microsoft Xtra Atoms

What I can see, you get a warning that writing Xtra Atoms fails, but that doesn’t mean Exiftool failed to write your data.

I tested with a PDF file adding Keywords, and it worked for me, even though I got the warning.

You can turn off writing Xtra Atoms under config.
Open config, select “Metadata” tab. Turn off: “Write Windows Xtra Atoms on Videos and Picture files”.

If you know Exiftool, you can even change how PhotoTags-Synchronizer should write data back to the PDF files. Open config, select the “Metadata” tab, then select “How to write Metadata”. 

I hope this helped.

If you still have issue, please let me know. Maybe you can share files you have issue with.

**Comment by Nordlien** [comment]
Uncheck this - so the application don't write Xtra Atoms 
![image](https://user-images.githubusercontent.com/72686779/209564763-b9430ed4-ff53-4c6e-bac2-bd0891ab9f3f.png)

**Comment by Nordlien** [comment]
How to change how Exiftool should write Keywords
![image](https://user-images.githubusercontent.com/72686779/209564844-791d0379-83f8-4d21-94f7-0236644351f9.png)
![image](https://user-images.githubusercontent.com/72686779/209564868-26922097-67ca-498f-a31e-22cb646d7afa.png)

**Comment by Nordlien** [comment]
Hi, I have uploaded a new version of the app so you will not see the warnings anymore for PDF files.

**Comment by cao-muc** [comment]
Wow, thank you!
I will try how it works, tomorrow!

⁣Sent from my mobile.​

**Comment by Nordlien** [comment]
You are welcome.It's loaded, and still being processed by Microsoft, I guess the us takes up to 24 hours. 2. jan. 2023 17:03 skrev cao-muc ***@***.***>:

Wow, thank you!

I will try how it works, tomorrow!



⁣Sent from my mobile.​
